/*
 * Chatter
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AuthLoginPayload struct for AuthLoginPayload
type AuthLoginPayload struct {
	Email string `json:"email"`
	Password string `json:"password"`
}
